### ISSUE TITLE
Exporting batch 2D segmentations

### ISSUE THREAD

**Issue by JemimaBurden** [volume-em/empanada-napari#14]
Firstly, thank you, I am loving Empanda's 2d and 3d predictions!

I have managed to use the 3D predictions (semantic only) with some level of success on 3D (serial 2D) SEM array tomography data and managed to save it and get it into Image J and then Amira  (my current go-to 3D visualisation software).

However, when I try the 2D predictions (batch) on a stack of TEM data (not serial images), whilst the segmentation works as before, I can't seem to save it in a way that other software can see the segmentations. Apoolgies - is this a napari question or an empanda question? Alternatively, can you let me know what I am doing wrong and what I need to do to fix it!

Thanks again in advance for all your help!

**Comment by conradry** [comment]
There seem to be two issues. First, the segmentations are output as 64-bit integers which isn't supported by all software (Fiji loaded the 64-bit images but required clicking through a few menus). Second, each segmentation has an extra dimension in order to correctly render them in the napari viewer (e.g., a 1000x1000 image has a segmentation of shape 1x1000x1000).

I've fixed the first issue such that segmentations will now save as 32-bit unsigned integers. That fix will take effect in a future release coming soon. The second issue is more on napari's side and I'll have to research ways to handle it.

In the meantime, I have a work around:

1. Open the Python console from the menu in the bottom left:

![console](https://user-images.githubusercontent.com/20257674/169558819-77e90e0b-81ad-4290-a826-f6e7ddeae5f8.png)


2. Paste and run this code

```python
import numpy as np
for layer in viewer.layers:
    if type(layer) == napari.layers.Labels:
        layer.data = layer.data.astype(np.uint32).squeeze()
```

You'll notice that this really screws up the visualization of the segmentations, so only do it right before you're ready for export. I've verified that they will open in Fiji after saving.

**Comment by akdess** [comment]
Hi thanks a lot for developing this tool!

I am also trying to save batch-mode MitoNet predictions, I can save them as you suggested through Pythion console but it is saved as tiff. I need to save it as svg. I would appreciate if you can provide a code for saving all segmantations as svg. Thanks!
