### ISSUE TITLE
Suggestion: add inference for series of images

### ISSUE THREAD

**Issue by programerkotik** [volume-em/empanada-napari#7]
Hi, 

this is not explicitly an issue but I wonder if you added the option to analyze multiple 2D images in one run. Usually, I work with them as with 3D stack, though this is not "real" 3D and I still need to segment only each XY axis separately. Is there a way to do so in the current Empanada version? 

Besides that, I am having trouble with running the Empanada plugin more than one time with one napari session. (I run napari from Jupiter notebook)

Warmest regards
Anna

**Comment by conradry** [comment]
Hi Anna,

That's a great suggestion. I added a check box in the 2D Inference widget named "Batch mode" that does exactly that. You can install the updated version in napari or with pip:

```shell
pip install empanada-napari==0.1.3
```

I tested launching napari from a Jupyter notebook and was able to run the plugin multiple times. Maybe try upgrading the plugin and see if that fixes the issue? Otherwise, please share the snippet of code that you're using to launch napari so that maybe I can reproduce it.

Best,
Ryan

**Comment by programerkotik** [comment]
Hi Ryan,

Thanks a lot for editing the plugin. I tested it and it works just fine. The only small issue is that the output is added to napari layers as separate images. During work with large datasets, it can be pretty annoying. Maybe adding the output as a single stack is much a better solution. 
Anyway, I run your plugin on the dataset from TEM where I needed to segment mitochondria and I am really impressed by how well it performs without any additional training. I really appreciate your work. 

P.S: After all, I had to reinstall the whole conda env which I was working with incl. napari and empanada and the issue with Jupyter notebook disappeared. 

Best,
Anna
